### ISSUE TITLE
mapUrl requirment

### ISSUE THREAD

**Issue by joshuacrowley** [IcanDivideBy0/react-tiled#2]
Great package, excited to try it out.

Bit confused about the MapProvider? Looks like it needs a mapUrl, looks like you're expecting an absolute url to the .json from Tiled. Is there anything else you're expecting in that directory, like the images? Does the mapPath variable need to be the name of the folder of assets?

Could I just import the JSON file and add it as a prop to the Map component?

I've had trouble getting the demo files to run as well, do you know if they're up to date?

**Comment by IcanDivideBy0** [comment]
Hi,
Yes, mapUrl should be an absolute path (it needs to be absolute, so the package can load images with relative path from the json more easily). The demo seems fine to me, run `yarn install && yarn build` in the the root folder, then `yarn install && yarn start` in the demo folder.

Still I must advice that I wrote this as a test just for fun. If you plan to do some fancy stuff, I strongly advice you to use some other solution involving canvas. I think most JS 2D game engines handle tiled maps nowadays, if you want to build it yourself, you can take a look at how I've done it here: https://github.com/IcanDivideBy0/bombersplash/blob/master/client/src/modules/game/components/GameCanvas.js#L114-L308
